//! Embeds assets/icons/**/*.png (the icon set inherited from mamepgui 1.8.2)
//! into the binary as a `&[(&str, &[u8])]` table, consumed by src/icons.rs.

use std::path::{Path, PathBuf};

fn main() {
    // The build script's cwd is not guaranteed to be the crate root, so anchor
    // on CARGO_MANIFEST_DIR (which is the repo root for this single-crate
    // layout). Resolving `assets/icons` relatively once scanned a directory
    // that did not exist, silently produced an empty table and left every icon
    // on the procedural fallback.
    let crate_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = crate_dir.join("assets/icons");
    let root = root
        .canonicalize()
        .unwrap_or_else(|e| panic!("assets/icons not found at {}: {e}", root.display()));
    println!("cargo:rerun-if-changed={}", root.display());

    let mut files: Vec<PathBuf> = Vec::new();
    collect(&root, &mut files);
    files.sort();
    if files.is_empty() {
        panic!("no .png found under {}", root.display());
    }

    let mut out = String::from(
        "// generated by build.rs — do not edit\n\
         pub static ICONS: &[(&str, &[u8])] = &[\n",
    );
    for f in &files {
        let key = f
            .strip_prefix(&root)
            .unwrap_or(f)
            .to_string_lossy()
            .replace('\\', "/");
        let abs = std::fs::canonicalize(f).expect("canonicalize icon");
        // `canonicalize` on Windows returns an extended-length path (`\\?\C:\…`);
        // drop the prefix so the literal stays a plain absolute path
        let lit = abs.to_string_lossy().replace('\\', "/");
        let lit = lit.strip_prefix("//?/").unwrap_or(&lit).to_string();
        out.push_str(&format!("    (\"{key}\", include_bytes!(\"{lit}\")),\n"));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("icon_assets.rs");
    std::fs::write(dest, out).unwrap();

    // Windows resources: the exe/taskbar icon plus the version strings
    // (successor of res/mamep.ico, which the 1.8.2 binary embedded the same way).
    // A failure here is reported but must not break the build — windres is only
    // present on a MinGW toolchain.
    if std::env::var("CARGO_CFG_WINDOWS").is_ok() {
        // assets/images 只放"内容图"（mame.png 占位图、logo、旧版品牌素材）；
        // 程序图标属于 icons 树，和 build.rs 扫描的那套图标资源同源。
        let ico = crate_dir.join("assets/icons/app.ico");
        if ico.exists() {
            let mut res = winresource::WindowsResource::new();
            res.set_icon(&ico.to_string_lossy());
            res.set("ProductName", "MvUI");
            res.set("FileDescription", "MvUI — MAME frontend");
            res.set("OriginalFilename", "mvui.exe");
            res.set("FileVersion", "1.0.0.0");
            res.set("ProductVersion", "1.0.0.0");
            match res.compile() {
                Ok(()) => println!("cargo:rerun-if-changed={}", ico.display()),
                Err(e) => println!("cargo:warning=resource compile failed: {e}"),
            }
        }
    }
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(&p, out);
        } else if p.extension().map(|x| x == "png").unwrap_or(false) {
            out.push(p);
        }
    }
}
