// Verify the DAT byte-range index against the original linear scan.
//
// Generates a history.dat-shaped file with the awkward cases in it, then times
// and compares both extraction paths. Run from mamegui-rs/:
//
//     cargo run --release --example datindex_bench

use std::time::Instant;

use mamegui_core::dat::{self, DOCK_HISTORY};
use mamegui_core::datindex;

fn main() {
    let dir = std::env::temp_dir().join("mamepgui-datbench");
    let _ = std::fs::create_dir_all(&dir);
    let path = dir.join("history.dat");

    // ~20 MB, 40k records, every third one sharing a tag with its neighbour so
    // the greedy-span case is exercised at scale
    let mut s = String::with_capacity(24 * 1024 * 1024);
    s.push_str("# generated by datindex_bench\n");
    for i in 0..40_000 {
        if i % 3 == 0 {
            s.push_str(&format!("$info=game{i},alt{i}\n"));
        } else {
            s.push_str(&format!("$info=game{i}\n"));
        }
        s.push_str(&format!("Game {i} was released by a company in {}.\n", 1970 + i % 50));
        s.push_str("$<a href=http://example.test/x>link line</a>\n");
        // pad so the file reaches a realistic size
        for p in 0..12 {
            s.push_str(&format!("detail line {p} for game {i}\n"));
        }
    }
    std::fs::write(&path, &s).unwrap();
    let bytes = std::fs::read(&path).unwrap();
    println!("fixture: {} records, {:.1} MB", 40_000, bytes.len() as f64 / 1e6);

    // ---- build the index once (this is the cost the scan pays every time) ----
    let t = Instant::now();
    let idx = datindex::DatIndex::build(&bytes);
    let build_ms = t.elapsed().as_secs_f64() * 1000.0;
    println!("index build:      {build_ms:8.2} ms  ({} tags)", idx.tags());

    // ---- equivalence over a spread of tags, including shared and missing ----
    let mut checked = 0;
    let mut mismatches = 0;
    for i in (0..40_000).step_by(997) {
        // `alt{i}` only exists every third record — that is the shared-tag case
        let mut tags = vec![format!("game{i}")];
        if i % 3 == 0 {
            tags.push(format!("alt{i}"));
        }
        for tag in tags {
            let scan = dat::get_history(&bytes, &tag, DOCK_HISTORY, true, "");
            let Some(range) = idx.lookup(&tag) else {
                println!("  MISSING in index: {tag}");
                mismatches += 1;
                continue;
            };
            let via = datindex::record_text(&bytes, range, &tag, true);
            let via = dat::finish_record(via, &tag, DOCK_HISTORY, true);
            if via != scan {
                mismatches += 1;
                if mismatches <= 3 {
                    println!("  MISMATCH {tag}\n    scan: {scan:?}\n    index:{via:?}");
                }
            }
            checked += 1;
        }
    }
    // a tag that does not exist at all
    let scan = dat::get_history(&bytes, "no_such_game", DOCK_HISTORY, true, "");
    if idx.lookup("no_such_game").is_some() || !scan.is_empty() {
        mismatches += 1;
        println!("  MISMATCH on a missing tag");
    }
    println!("equivalence:      {checked} tags compared, {mismatches} mismatches");

    // ---- per-lookup cost: full scan vs indexed read ----
    let probes: Vec<String> = (0..40_000).step_by(997).map(|i| format!("game{i}")).collect();

    let t = Instant::now();
    for tag in &probes {
        let _ = dat::get_history(&bytes, tag, DOCK_HISTORY, true, "");
    }
    let scan_total = t.elapsed().as_secs_f64() * 1000.0;

    let t = Instant::now();
    for tag in &probes {
        let _ = datindex::history_indexed(&path, tag, DOCK_HISTORY, true, "");
    }
    let idx_total = t.elapsed().as_secs_f64() * 1000.0;

    let n = probes.len() as f64;
    println!("\n{} lookups over a {:.0} MB file:", probes.len(), bytes.len() as f64 / 1e6);
    println!("  linear scan:     {scan_total:8.2} ms total  ({:6.3} ms/lookup)", scan_total / n);
    println!("  indexed read:    {idx_total:8.2} ms total  ({:6.3} ms/lookup)", idx_total / n);
    println!("  speed-up:        {:8.1}x", scan_total / idx_total.max(1e-9));
    println!("  (index build is paid once: {build_ms:.0} ms)");

    // how big are the ranges we actually read?
    let mut total = 0usize;
    let mut maxr = 0usize;
    for tag in &probes {
        if let Some(r) = idx.lookup(tag) {
            let n = r.end - r.start;
            total += n;
            maxr = maxr.max(n);
        }
    }
    println!(
        "  range sizes:     avg {:6.0} B, max {:6.0} B (file is {:.0} MB)",
        total / probes.len().max(1),
        maxr,
        bytes.len() as f64 / 1e6
    );

    // cache diagnostics: the whole benefit depends on the second lookup onward
    datindex::clear_dat_cache();
    let t = Instant::now();
    let _ = datindex::history_indexed(&path, &probes[0], DOCK_HISTORY, true, "");
    let cold = t.elapsed().as_secs_f64() * 1000.0;
    let t = Instant::now();
    for tag in &probes {
        let _ = datindex::history_indexed(&path, tag, DOCK_HISTORY, true, "");
    }
    let warm_total = t.elapsed().as_secs_f64() * 1000.0;
    println!("\n  cold first lookup (builds): {:6.2} ms", cold);
    println!("  warm lookups ({n} total):    {:6.2} ms  ({:6.3} ms/lookup)", warm_total, warm_total / n);
    println!("  warm speed-up vs scan:      {:8.1}x", scan_total / warm_total.max(1e-9));

    datindex::clear_dat_cache();
    let _ = std::fs::remove_file(&path);
    if mismatches == 0 {
        println!("\nOK: index output identical to the scan on every tag");
    } else {
        std::process::exit(1);
    }
}
