//! Icon registry over the PNG set inherited from the original GUI (1.8.2)
//! (design doc §9.2). Files under `assets/icons/` are embedded by build.rs;
//! the procedural squares below stay as the fallback when a file is missing.
//!
//! 两个资源树的分工（2026-10-05 整理过一次）：
//! - `assets/icons/`   → build.rs 扫进 `ICONS` 表，按相对路径取图（本文件）
//! - `assets/images/`  → 内容图，单独 `include_bytes!` 引入（占位图 mame.png、
//!   关于框的 logo.png、程序/exe 图标 app.ico）

use egui::{Color32, Vec2};
use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

// generated by build.rs: `pub static ICONS: &[(&str, &[u8])]`
include!(concat!(env!("OUT_DIR"), "/icon_assets.rs"));

static BY_NAME: OnceLock<HashMap<&'static str, &'static [u8]>> = OnceLock::new();
static TEXTURES: OnceLock<Mutex<HashMap<&'static str, egui::TextureHandle>>> = OnceLock::new();

fn table() -> &'static HashMap<&'static str, &'static [u8]> {
    BY_NAME.get_or_init(|| ICONS.iter().copied().collect())
}

// Status square colours, sampled from the 1.8.2 `16x16/sqr-g|y|r.png` so the
// procedural fallback matches the PNG set.
pub const GREEN: Color32 = Color32::from_rgb(0x1f, 0xc3, 0x00);
pub const YELLOW: Color32 = Color32::from_rgb(0xee, 0xaa, 0x23);
pub const RED: Color32 = Color32::from_rgb(0xc3, 0x21, 0x00);
pub const GRAY: Color32 = Color32::from_rgb(0x80, 0x80, 0x80);

/// square filled with a flat colour (origin: GameListDelegate's status pixmap)
pub fn draw_square(ui: &mut egui::Ui, color: Color32, size: f32) -> egui::Response {
    let (rect, resp) = ui.allocate_exact_size(Vec2::splat(size), egui::Sense::click());
    ui.painter().rect_filled(rect, 1.0, color);
    resp
}

/// decoded + uploaded texture, cached by name
pub fn texture(ctx: &egui::Context, name: &str) -> Option<egui::TextureHandle> {
    if let Some(t) = TEXTURES
        .get_or_init(Default::default)
        .lock()
        .ok()
        .and_then(|m| m.get(name).cloned())
    {
        return Some(t);
    }
    // reuse the &'static str key from the generated table
    let key = *table().keys().find(|k| **k == name)?;
    let raw = table().get(key).copied()?;
    let img = image::load_from_memory(raw).ok()?;
    let rgba = img.to_rgba8();
    let tex = ctx.load_texture(
        name.to_string(),
        egui::ColorImage::from_rgba_unmultiplied(
            [rgba.width() as usize, rgba.height() as usize],
            rgba.as_flat_samples().as_slice(),
        ),
        egui::TextureOptions::LINEAR,
    );
    let mut m = TEXTURES.get_or_init(Default::default).lock().ok()?;
    Some(m.entry(key).or_insert(tex).clone())
}

/// 图片框的占位图（`assets/images/mame.png`，240×180）。
///
/// 游戏没有对应的截图/标题图/机台图等素材时，就显示这一张，而不是画一个空框。
/// 自己解码上传、不走 egui 的 `include_image!` 字节源：那条路要等 egui 的字节
/// loader 就绪，未就绪时 `egui::Image` 会画出自带的 ⚠ 兜底字形
/// （`windows.rs::draw_app_logo` 里踩过同一个坑）。
fn placeholder_texture(ctx: &egui::Context) -> Option<egui::TextureHandle> {
    static TEX: OnceLock<Mutex<Option<egui::TextureHandle>>> = OnceLock::new();
    let mut slot = TEX.get_or_init(|| Mutex::new(None)).lock().ok()?;
    if let Some(t) = slot.clone() {
        return Some(t);
    }
    // 编译期内嵌：mame.png 不在 assets/icons 下，build.rs 的图标表扫不到它
    const RAW: &[u8] = include_bytes!("../assets/images/mame.png");
    let rgba = image::load_from_memory(RAW).ok()?.to_rgba8();
    let tex = ctx.load_texture(
        "placeholder-mame",
        egui::ColorImage::from_rgba_unmultiplied(
            [rgba.width() as usize, rgba.height() as usize],
            rgba.as_flat_samples().as_slice(),
        ),
        egui::TextureOptions::LINEAR,
    );
    *slot = Some(tex.clone());
    Some(tex)
}

/// 画整张纹理时该传的 uv 矩形。
///
/// **uv 是归一化的 0..1，不是像素尺寸**（egui 0.29 `painter.rs:435` 文档原话）。
/// 曾三处写成 `Rect::from_min_size(Pos2::ZERO, tex.size_vec2())`，采样全落在
/// 纹理外 + 默认 `ClampToEdge` → clamp 到边缘像素（logo 边缘恰好全透明）→
/// **整张图凭空消失，而且不报错**。
pub fn full_uv() -> egui::Rect {
    egui::Rect::from_min_max(egui::Pos2::ZERO, egui::pos2(1.0, 1.0))
}

/// 在 `rect` 内居中画占位图，保持原比例；画不出来返回 false。
///
/// 不无限放大：240×180 的图铺满一个大 dock 会糊成一片，最多放大 2 倍。
pub fn draw_placeholder(ui: &mut egui::Ui, rect: egui::Rect) -> bool {
    let ctx = ui.ctx().clone();
    let Some(tex) = placeholder_texture(&ctx) else {
        return false;
    };
    let size = tex.size_vec2();
    if size.x <= 0.0 || size.y <= 0.0 || rect.width() <= 0.0 || rect.height() <= 0.0 {
        return false;
    }
    let scale = (rect.width() / size.x).min(rect.height() / size.y).min(2.0);
    let drawn = egui::Rect::from_center_size(rect.center(), size * scale);
    ui.painter().image(tex.id(), drawn, full_uv(), Color32::WHITE);
    true
}

/// draw an icon scaled to `size`; returns None when the name is unknown
pub fn draw(
    ui: &mut egui::Ui,
    ctx: &egui::Context,
    name: &str,
    size: f32,
) -> Option<egui::Response> {
    let tex = texture(ctx, name)?;
    Some(ui.add(egui::Image::new(&tex).max_size(Vec2::splat(size))))
}

/// Like [`draw`], but the image claims no interaction at all.
///
/// egui's `Image` defaults to `Sense::hover()`, which would win the hover/press
/// against the row-wide band the folder tree paints behind it — the icon would
/// become a dead zone the row no longer reacts to.
pub fn draw_passive(ui: &mut egui::Ui, ctx: &egui::Context, name: &str, size: f32) {
    if let Some(tex) = texture(ctx, name) {
        ui.add(
            egui::Image::new(&tex)
                .max_size(Vec2::splat(size))
                .sense(egui::Sense { click: false, drag: false, focusable: false }),
        );
    }
}

/// 在 `rect` 里画图标，**不推进布局游标**，画不出来返回 false。
///
/// # 为什么不能走 `ui.put`
///
/// `Ui::put(rect, widget)` 的文档说"allocate a specific part of the Ui"，
/// 听着像纯定位，但它的实现（egui 0.29 `ui.rs:1617`）是
/// `allocate_new_ui(.., |ui| ui.add(widget))`，而 `allocate_new_ui`
/// 结尾有一句 `self.placer.advance_after_rects(rect, rect, item_spacing)`
/// —— **它照样把游标往前推**。而且推的量取决于 rect 的位置：rect 越靠右，
/// 游标被推得越远。
///
/// 在 Rom 面板里这个副作用是**肉眼可见的错位**（用户 2026-10-06 截图）：
/// `state_with_icon` 先 `allocate_space` 死占状态列宽，紧接着调本函数画图标，
/// 于是 crc 列的起点被多推了"图标右边缘 - 状态列左边缘"那么多。这个量随
/// 状态词宽变化（「拥有」比「缺失」窄），于是**同一屏里每一行的 crc 与
/// 区域列起点都不同**——整列参差不齐。
///
/// 探针实测（`examples/col_probe.rs`，让 egui 自己算而不是推理）：
///
/// |画图标的方式|crc 起点（拥有 / 缺失 / 未 dump）|
/// |---|---|
/// |`ui.put`（旧）|**150 / 163 / 172** ——逐行漂|
/// |`painter().image`（现在）|**148 / 148 / 148** —— 一条竖线|
///
/// 所以这里必须用 `painter().image` 直接画：**只要不碰游标，位置就由
/// 调用方给的 rect 唯一决定**，与同行其他内容无关。
///
/// uv 用 [`full_uv`]（归一化 0..1）——传 `tex.size_vec2()` 会采样到纹理外，
/// ClampToEdge 兜底后整张图消失且不报错（这个坑踩过）。
pub fn put(
    ui: &mut egui::Ui,
    ctx: &egui::Context,
    name: &str,
    rect: egui::Rect,
) -> bool {
    let Some(tex) = texture(ctx, name) else { return false };
    ui.painter()
        .image(tex.id(), rect, full_uv(), Color32::WHITE);
    true
}

/// inline icon for command.dat notation, falling back to the glyph
pub fn notation_icon(
    ui: &mut egui::Ui,
    n: &crate::core::dat::Notation,
    size: f32,
) -> bool {
    let Some(name) = notation_file(n) else { return false };
    let ctx = ui.ctx().clone();
    draw(ui, &ctx, name, size).is_some()
}

fn notation_file(n: &crate::core::dat::Notation) -> Option<&'static str> {
    use crate::core::dat::Notation::*;
    Some(match n {
        Dir(1) => "16x16/dir-1.png",
        Dir(2) => "16x16/dir-2.png",
        Dir(3) => "16x16/dir-3.png",
        Dir(4) => "16x16/dir-4.png",
        Dir(5) => "16x16/dir-5.png",
        Dir(6) => "16x16/dir-6.png",
        Dir(7) => "16x16/dir-7.png",
        Dir(8) => "16x16/dir-8.png",
        Dir(9) => "16x16/dir-9.png",
        Dir(_) => "16x16/blank.png",
        Hcf => "16x16/dir-hcf.png",
        Hcb => "16x16/dir-hcb.png",
        Qdf => "16x16/dir-qdf.png",
        Qdb => "16x16/dir-qdb.png",
        StarGold => "16x16/star_gold.png",
        StarSilver => "16x16/star_silver.png",
        TriRed => "16x16/tri-r.png",
        CircleGreen => "16x16/cir-g.png",
        CircleYellow => "16x16/cir-y.png",
        CircleRed => "16x16/cir-r.png",
        Arrow => "16x16/arrow-r.png",
        // Buttons render as colored glyph letters, not PNGs: the shipped
        // btn-*.png bitmaps are mislabelled art — btn-B.png paints a "P",
        // btn-na.png a "1", btn-nb.png an "A", btn-nd.png a "4" — so a combo
        // like `_B` showed a P and `_a` showed a 1 (user report 2026-10-07,
        // 三国战纪 command.dat). The glyph fallback always shows the letter
        // the notation actually stands for, which is the only thing that
        // matters in a move list.
        Button(_) | ButtonN(_) => return None,
    })
}

/// status colour for a driver grade (list rows + status bar squares).
/// Painted procedurally (`draw_square`), not from the 16×16 `sqr-*.png`
/// bitmaps: a solid block has no detail, and direct painting stays crisp
/// at every DPI where the bitmap was 2× upscaled on a 4K screen.
pub fn status_color(grade: u8) -> Color32 {
    match grade {
        crate::core::model::STATUS_GOOD => GREEN,
        crate::core::model::STATUS_IMPERFECT => YELLOW,
        crate::core::model::STATUS_PRELIMINARY => RED,
        _ => GRAY,
    }
}

pub const FOLDER: &str = "32x32/folder.png";

/// glyph fallback for `_A`..`_S` / `_+` (origin: btn-<CHAR>.png).
/// A static table on purpose: this sits on the per-frame render path, and the
/// previous `Box::leak(format!(...))` leaked one allocation per notation/frame.
fn button_glyph(b: &str) -> &'static str {
    match b {
        "A" => "A",
        "B" => "B",
        "C" => "C",
        "D" => "D",
        "G" => "G",
        "K" => "K",
        "N" => "N",
        "P" => "P",
        "S" => "S",
        "+" => "+",
        _ => "?",
    }
}

/// glyph fallback for `_a`..`_f` (origin: btn-n<lower>.png)
fn button_glyph_n(b: &str) -> &'static str {
    match b {
        "a" | "A" => "a",
        "b" | "B" => "b",
        "c" | "C" => "c",
        "d" | "D" => "d",
        "e" | "E" => "e",
        "f" | "F" => "f",
        _ => "?",
    }
}

pub fn notation_glyph(n: &crate::core::dat::Notation) -> (&'static str, Color32) {
    use crate::core::dat::Notation::*;
    match n {
        Dir(1) => ("↙", GREEN),
        Dir(2) => ("↓", GREEN),
        Dir(3) => ("↘", GREEN),
        Dir(4) => ("←", GREEN),
        Dir(6) => ("→", GREEN),
        Dir(7) => ("↖", GREEN),
        Dir(8) => ("↑", GREEN),
        Dir(9) => ("↗", GREEN),
        Dir(_) => ("•", GREEN),
        Hcf => ("↻", YELLOW),
        Hcb => ("↺", YELLOW),
        Qdf => ("⤸", YELLOW),
        Qdb => ("⤹", YELLOW),
        Button(b) => (button_glyph(b), Color32::from_rgb(0xff, 0x9d, 0x5c)),
        ButtonN(b) => (
            button_glyph_n(b),
            Color32::from_rgb(0xc9, 0x7b, 0x4b),
        ),
        StarGold => ("★", Color32::from_rgb(0xff, 0xd7, 0x00)),
        StarSilver => ("☆", Color32::from_rgb(0xc0, 0xc0, 0xc0)),
        TriRed => ("▲", RED),
        CircleYellow => ("○", YELLOW),
        CircleRed => ("◎", RED),
        CircleGreen => ("●", GREEN),
        Arrow => ("→", GRAY),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// uv 是**归一化的 0..1**，不是像素尺寸。
    ///
    /// 三处调用曾写成 `Rect::from_min_size(Pos2::ZERO, tex.size_vec2())`：采样
    /// 全落在纹理之外，加上默认的 `ClampToEdge` 会被夹到边缘像素上，而 logo
    /// 的边缘恰好全是透明像素 → **整张图凭空消失，而且不报错**。只有测试能
    /// 抓住这种失败。
    #[test]
    fn full_uv_is_normalized() {
        let uv = full_uv();
        assert_eq!(uv.min, egui::Pos2::ZERO);
        assert_eq!(uv.max, egui::pos2(1.0, 1.0));
        // 一张 240×180 的图也必须用同一矩形——尺寸不该出现在 uv 里
        assert_ne!(uv.size(), egui::vec2(240.0, 180.0));
    }

    /// 占位图是编译期内嵌的：路径写错或图坏了不会在编译期报出来，运行时
    /// `draw_placeholder` 只是安静地返回 false。这里把它解码一遍钉住。
    #[test]
    fn embedded_placeholder_decodes() {
        let img = image::load_from_memory(include_bytes!("../assets/images/mame.png")).unwrap();
        assert!(img.width() > 0 && img.height() > 0);
    }

    /// **`put` 绝不能推进布局游标（`LeftToRight` 行布局下）。**
    ///
    /// 这条钉的是一个已经真刀真枪发生过的错位（用户 2026-10-06 截图）：
    /// Rom面板的 crc / 区域两列看着没左对齐。
    ///
    /// 机制：`put` 原先走 `ui.put(rect, Image)`。它的文档说"allocate a
    /// specific part of the Ui"，听着像纯定位，但实现（egui 0.29
    /// `ui.rs:1617`）是 `allocate_new_ui(.., |ui| ui.add(widget))`，而
    /// `allocate_new_ui` 结尾有 `advance_after_rects` —— 在
    /// **`LeftToRight` 行布局里它会把游标推到那个 rect 的右边缘**。
    ///
    /// 于是 Rom 面板里：状态词越宽（「缺失」比「拥有」宽），图标越靠右，
    /// crc 列的起点被推得越远。**同一屏里每一行的 crc 与区域列起点都不同**，
    /// 整列参差 —— 截图里那台机器混着「缺失」「未 dump」「拥有」三种词。
    ///
    /// **测试必须在 `LeftToRight` 里跑，这点踩过一次**：第一版用
    /// `CentralPanel` 的默认布局（`TopDown`）写，实测 `ui.put` 在 TopDown
    /// 下Δx/Δy **都是 0**（游标只往下走，而 rect 在它右边），于是把`put`
    /// 改回`ui.put` 跑变异测试**照样全绿**。探针
    /// `examples/put_probe.rs` 把两种布局并排量了出来：
    ///
    /// |布局|`ui.put` 后的 Δcursor|
    /// |---|---|
    /// |`TopDown`|Δx=0, Δy=0|
    /// |**`LeftToRight`**|**Δx=148**|
    ///
    /// 探针 `examples/col_probe.rs` 是同一套量法，只是连列起点一起打。
    #[test]
    fn put_never_advances_the_layout_cursor() {
        let ctx = egui::Context::default();
        let name = "16x16/status_good.png";

        let _ = ctx.run(egui::RawInput::default(), |ctx| {
            egui::CentralPanel::default().show(ctx, |ui| {
                // **必须是 LeftToRight** —— `ui.put` 只在这个方向上推游标
                ui.scope_builder(
                    egui::UiBuilder::new().layout(egui::Layout::left_to_right(egui::Align::Min)),
                    |ui| {
                        ui.spacing_mut().item_spacing.x = 0.0;
                        ui.spacing_mut().item_spacing.y = 0.0;
                        for icon_x in [8.0_f32, 90.0, 200.0, 400.0] {
                            // 先死占一段，把游标推到确定位置
                            let (_id, _r) = ui.allocate_space(egui::vec2(60.0, 16.0));
                            let before = ui.cursor().min.x;
                            let rect = egui::Rect::from_min_size(
                                egui::pos2(icon_x, ui.cursor().min.y),
                                egui::vec2(16.0, 16.0),
                            );
                            // **只调 put 本身**，不要额外补一笔 painter 绘制 ——
                            // 补了的话两笔一加一减游标正好回到原位，测试就成了
                            // 摆设（这个也踩过一次）。
                            let _ = put(ui, ctx, name, rect);
                            let after = ui.cursor().min.x;
                            assert_eq!(
                                before, after,
                                "图标画在 x={icon_x} 时游标被推进了 {}px —— put 又变回 widget 了",
                                after - before
                            );
                        }
                    },
                );
            });
        });
    }

    /// `put` 在纹理**不存在**时也绝不能推游标。
    ///
    /// 上面那条走的是"查到纹理"的分支。而查不到时旧代码是提前 `return
    /// false`、根本没画—— 也就是说**两条分支的布局副作用可能不一致**，
    /// 而"图标忽隐忽现时版面就抖"是最难查的那种毛病。
    ///
    /// 同样必须在 `LeftToRight` 里跑（理由见上一条）。
    #[test]
    fn put_with_an_unknown_name_also_leaves_the_cursor_alone() {
        let ctx = egui::Context::default();
        let _ = ctx.run(egui::RawInput::default(), |ctx| {
            egui::CentralPanel::default().show(ctx, |ui| {
                ui.scope_builder(
                    egui::UiBuilder::new().layout(egui::Layout::left_to_right(egui::Align::Min)),
                    |ui| {
                        ui.spacing_mut().item_spacing.x = 0.0;
                        ui.spacing_mut().item_spacing.y = 0.0;
                        let (_id, _r) = ui.allocate_space(egui::vec2(60.0, 16.0));
                        let before = ui.cursor().min.x;
                        let rect = egui::Rect::from_min_size(
                            egui::pos2(120.0, ui.cursor().min.y),
                            egui::vec2(16.0, 16.0),
                        );
                        let drawn = put(ui, ctx, "16x16/there_is_no_such_icon.png", rect);
                        assert!(!drawn, "不存在的图标名必须返回 false，让调用方画退路");
                        assert_eq!(
                            before,
                            ui.cursor().min.x,
                            "查不到纹理时也不能推进游标 —— 否则图标加载前后版面会抖"
                        );
                    },
                );
            });
        });
    }
}
