//! Icon registry over the PNG set inherited from mamepgui 1.8.2
//! (design doc §9.2). Files under `assets/icons/` are embedded by build.rs;
//! the procedural squares below stay as the fallback when a file is missing.
//!
//! 两个资源树的分工（2026-10-05 整理过一次）：
//! - `assets/icons/`   → build.rs 扫进 `ICONS` 表，按相对路径取图（本文件）
//! - `assets/images/`  → 内容图，单独 `include_bytes!` 引入（占位图 mame.png、
//!   关于框的 logo.png、程序/exe 图标 app.ico）

use egui::{Color32, Vec2};
use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

// generated by build.rs: `pub static ICONS: &[(&str, &[u8])]`
include!(concat!(env!("OUT_DIR"), "/icon_assets.rs"));

static BY_NAME: OnceLock<HashMap<&'static str, &'static [u8]>> = OnceLock::new();
static TEXTURES: OnceLock<Mutex<HashMap<&'static str, egui::TextureHandle>>> = OnceLock::new();

fn table() -> &'static HashMap<&'static str, &'static [u8]> {
    BY_NAME.get_or_init(|| ICONS.iter().copied().collect())
}

// Status square colours, sampled from the 1.8.2 `16x16/sqr-g|y|r.png` so the
// procedural fallback matches the PNG set.
pub const GREEN: Color32 = Color32::from_rgb(0x1f, 0xc3, 0x00);
pub const YELLOW: Color32 = Color32::from_rgb(0xee, 0xaa, 0x23);
pub const RED: Color32 = Color32::from_rgb(0xc3, 0x21, 0x00);
pub const GRAY: Color32 = Color32::from_rgb(0x80, 0x80, 0x80);

/// square filled with a flat colour (origin: GameListDelegate's status pixmap)
pub fn draw_square(ui: &mut egui::Ui, color: Color32, size: f32) -> egui::Response {
    let (rect, resp) = ui.allocate_exact_size(Vec2::splat(size), egui::Sense::click());
    ui.painter().rect_filled(rect, 1.0, color);
    resp
}

/// decoded + uploaded texture, cached by name
pub fn texture(ctx: &egui::Context, name: &str) -> Option<egui::TextureHandle> {
    if let Some(t) = TEXTURES
        .get_or_init(Default::default)
        .lock()
        .ok()
        .and_then(|m| m.get(name).cloned())
    {
        return Some(t);
    }
    // reuse the &'static str key from the generated table
    let key = *table().keys().find(|k| **k == name)?;
    let raw = table().get(key).copied()?;
    let img = image::load_from_memory(raw).ok()?;
    let rgba = img.to_rgba8();
    let tex = ctx.load_texture(
        name.to_string(),
        egui::ColorImage::from_rgba_unmultiplied(
            [rgba.width() as usize, rgba.height() as usize],
            rgba.as_flat_samples().as_slice(),
        ),
        egui::TextureOptions::LINEAR,
    );
    let mut m = TEXTURES.get_or_init(Default::default).lock().ok()?;
    Some(m.entry(key).or_insert(tex).clone())
}

/// 图片框的占位图（`assets/images/mame.png`，240×180）。
///
/// 游戏没有对应的截图/标题图/机台图等素材时，就显示这一张，而不是画一个空框。
/// 自己解码上传、不走 egui 的 `include_image!` 字节源：那条路要等 egui 的字节
/// loader 就绪，未就绪时 `egui::Image` 会画出自带的 ⚠ 兜底字形
/// （`windows.rs::draw_app_logo` 里踩过同一个坑）。
fn placeholder_texture(ctx: &egui::Context) -> Option<egui::TextureHandle> {
    static TEX: OnceLock<Mutex<Option<egui::TextureHandle>>> = OnceLock::new();
    let mut slot = TEX.get_or_init(|| Mutex::new(None)).lock().ok()?;
    if let Some(t) = slot.clone() {
        return Some(t);
    }
    // 编译期内嵌：mame.png 不在 assets/icons 下，build.rs 的图标表扫不到它
    const RAW: &[u8] = include_bytes!("../assets/images/mame.png");
    let rgba = image::load_from_memory(RAW).ok()?.to_rgba8();
    let tex = ctx.load_texture(
        "placeholder-mame",
        egui::ColorImage::from_rgba_unmultiplied(
            [rgba.width() as usize, rgba.height() as usize],
            rgba.as_flat_samples().as_slice(),
        ),
        egui::TextureOptions::LINEAR,
    );
    *slot = Some(tex.clone());
    Some(tex)
}

/// 在 `rect` 内居中画占位图，保持原比例；画不出来返回 false。
///
/// 不无限放大：240×180 的图铺满一个大 dock 会糊成一片，最多放大 2 倍。
pub fn draw_placeholder(ui: &mut egui::Ui, rect: egui::Rect) -> bool {
    let ctx = ui.ctx().clone();
    let Some(tex) = placeholder_texture(&ctx) else {
        return false;
    };
    let size = tex.size_vec2();
    if size.x <= 0.0 || size.y <= 0.0 || rect.width() <= 0.0 || rect.height() <= 0.0 {
        return false;
    }
    let scale = (rect.width() / size.x).min(rect.height() / size.y).min(2.0);
    let drawn = egui::Rect::from_center_size(rect.center(), size * scale);
    ui.painter().image(
        tex.id(),
        drawn,
        egui::Rect::from_min_size(egui::Pos2::ZERO, size),
        Color32::WHITE,
    );
    true
}

/// draw an icon scaled to `size`; returns None when the name is unknown
pub fn draw(
    ui: &mut egui::Ui,
    ctx: &egui::Context,
    name: &str,
    size: f32,
) -> Option<egui::Response> {
    let tex = texture(ctx, name)?;
    Some(ui.add(egui::Image::new(&tex).max_size(Vec2::splat(size))))
}

/// Like [`draw`], but the image claims no interaction at all.
///
/// egui's `Image` defaults to `Sense::hover()`, which would win the hover/press
/// against the row-wide band the folder tree paints behind it — the icon would
/// become a dead zone the row no longer reacts to.
pub fn draw_passive(ui: &mut egui::Ui, ctx: &egui::Context, name: &str, size: f32) {
    if let Some(tex) = texture(ctx, name) {
        ui.add(
            egui::Image::new(&tex)
                .max_size(Vec2::splat(size))
                .sense(egui::Sense { click: false, drag: false, focusable: false }),
        );
    }
}

/// draw an icon into an explicit rect, without advancing the layout cursor
/// (used for the "unavailable" badge painted on top of the status square)
pub fn put(
    ui: &mut egui::Ui,
    ctx: &egui::Context,
    name: &str,
    rect: egui::Rect,
) -> bool {
    let Some(tex) = texture(ctx, name) else { return false };
    ui.put(rect, egui::Image::new(&tex).fit_to_exact_size(rect.size()));
    true
}

/// inline icon for command.dat notation, falling back to the glyph
pub fn notation_icon(
    ui: &mut egui::Ui,
    n: &crate::core::dat::Notation,
    size: f32,
) -> bool {
    let Some(name) = notation_file(n) else { return false };
    let ctx = ui.ctx().clone();
    draw(ui, &ctx, name, size).is_some()
}

fn notation_file(n: &crate::core::dat::Notation) -> Option<&'static str> {
    use crate::core::dat::Notation::*;
    Some(match n {
        Dir(1) => "16x16/dir-1.png",
        Dir(2) => "16x16/dir-2.png",
        Dir(3) => "16x16/dir-3.png",
        Dir(4) => "16x16/dir-4.png",
        Dir(5) => "16x16/dir-5.png",
        Dir(6) => "16x16/dir-6.png",
        Dir(7) => "16x16/dir-7.png",
        Dir(8) => "16x16/dir-8.png",
        Dir(9) => "16x16/dir-9.png",
        Dir(_) => "16x16/blank.png",
        Hcf => "16x16/dir-hcf.png",
        Hcb => "16x16/dir-hcb.png",
        Qdf => "16x16/dir-qdf.png",
        Qdb => "16x16/dir-qdb.png",
        StarGold => "16x16/star_gold.png",
        StarSilver => "16x16/star_silver.png",
        TriRed => "16x16/tri-r.png",
        CircleGreen => "16x16/cir-g.png",
        CircleYellow => "16x16/cir-y.png",
        CircleRed => "16x16/cir-r.png",
        Arrow => "16x16/arrow-r.png",
        // origin: `_([A-DGKNPS+])` → btn-<CHAR>.png
        Button(c) => match c.as_str() {
            "A" => "16x16/btn-A.png",
            "B" => "16x16/btn-B.png",
            "C" => "16x16/btn-C.png",
            "D" => "16x16/btn-D.png",
            "G" => "16x16/btn-G.png",
            "K" => "16x16/btn-K.png",
            "N" => "16x16/btn-N.png",
            "P" => "16x16/btn-P.png",
            "S" => "16x16/btn-S.png",
            "+" => "16x16/btn-+.png",
            _ => return None,
        },
        // origin: `_([a-f])` → btn-na..nf.png
        ButtonN(c) => match c.as_str() {
            "a" | "A" => "16x16/btn-na.png",
            "b" | "B" => "16x16/btn-nb.png",
            "c" | "C" => "16x16/btn-nc.png",
            "d" | "D" => "16x16/btn-nd.png",
            "e" | "E" => "16x16/btn-ne.png",
            "f" | "F" => "16x16/btn-nf.png",
            _ => return None,
        },
    })
}

/// status colour for a driver grade (list rows + status bar squares).
/// Painted procedurally (`draw_square`), not from the 16×16 `sqr-*.png`
/// bitmaps: a solid block has no detail, and direct painting stays crisp
/// at every DPI where the bitmap was 2× upscaled on a 4K screen.
pub fn status_color(grade: u8) -> Color32 {
    match grade {
        crate::core::model::STATUS_GOOD => GREEN,
        crate::core::model::STATUS_IMPERFECT => YELLOW,
        crate::core::model::STATUS_PRELIMINARY => RED,
        _ => GRAY,
    }
}

pub const FOLDER: &str = "32x32/folder.png";

/// glyph fallback for `_A`..`_S` / `_+` (origin: btn-<CHAR>.png).
/// A static table on purpose: this sits on the per-frame render path, and the
/// previous `Box::leak(format!(...))` leaked one allocation per notation/frame.
fn button_glyph(b: &str) -> &'static str {
    match b {
        "A" => "A",
        "B" => "B",
        "C" => "C",
        "D" => "D",
        "G" => "G",
        "K" => "K",
        "N" => "N",
        "P" => "P",
        "S" => "S",
        "+" => "+",
        _ => "?",
    }
}

/// glyph fallback for `_a`..`_f` (origin: btn-n<lower>.png)
fn button_glyph_n(b: &str) -> &'static str {
    match b {
        "a" | "A" => "a",
        "b" | "B" => "b",
        "c" | "C" => "c",
        "d" | "D" => "d",
        "e" | "E" => "e",
        "f" | "F" => "f",
        _ => "?",
    }
}

pub fn notation_glyph(n: &crate::core::dat::Notation) -> (&'static str, Color32) {
    use crate::core::dat::Notation::*;
    match n {
        Dir(1) => ("↙", GREEN),
        Dir(2) => ("↓", GREEN),
        Dir(3) => ("↘", GREEN),
        Dir(4) => ("←", GREEN),
        Dir(6) => ("→", GREEN),
        Dir(7) => ("↖", GREEN),
        Dir(8) => ("↑", GREEN),
        Dir(9) => ("↗", GREEN),
        Dir(_) => ("•", GREEN),
        Hcf => ("↻", YELLOW),
        Hcb => ("↺", YELLOW),
        Qdf => ("⤸", YELLOW),
        Qdb => ("⤹", YELLOW),
        Button(b) => (button_glyph(b), Color32::from_rgb(0xff, 0x9d, 0x5c)),
        ButtonN(b) => (
            button_glyph_n(b),
            Color32::from_rgb(0xc9, 0x7b, 0x4b),
        ),
        StarGold => ("★", Color32::from_rgb(0xff, 0xd7, 0x00)),
        StarSilver => ("☆", Color32::from_rgb(0xc0, 0xc0, 0xc0)),
        TriRed => ("▲", RED),
        CircleYellow => ("○", YELLOW),
        CircleRed => ("◎", RED),
        CircleGreen => ("●", GREEN),
        Arrow => ("→", GRAY),
    }
}
